### ISSUE TITLE
Buggy vanilla taiga

### ISSUE THREAD

**Issue by Rad233** [ApolloDatapacks/tectonic#11]
Game version: 1.18.2 fabric
Mod version: 1.1
Environment: Heavy modded(291 mods)
Other biome mods: Terralith v2.2.3
Screenshot:
https://i.postimg.cc/hjmdp4Ds/2022-12-21-12-18-33.png

**Comment by ApolloDatapacks** [comment]
Can you provide your mods list?

**Comment by Rad233** [comment]
Modlist: https://i.postimg.cc/9FXJLXLr/modlist.png
Sorry, I'm not a mod dev so I couldn't figure out how this mod works. Searching modlist for conflicting mods may be a heavy load to you. I'll try to narrow down the mod range.

**Comment by Rad233** [comment]
I tested out that the mod causing the bug is Terralith v2.2.3, and there's another bug: Tectonic mod is causing modded structures loading inappropriatly. I'll test out the mod causing it then.

**Comment by Rad233** [comment]
And there's another bug, I tested with only fabric api and Tectonic mod, the world was generated with same seed.
Screenshot: https://i.postimg.cc/XqN6d4WM/image.png
