### ISSUE TITLE
Temperature of some biomes are off

### ISSUE THREAD

**Issue by Menlor** [ApolloDatapacks/tectonic#12]
Using Tectonic 1.1.2 for Minecraft 1.18.2.

Some of the biome temperatures seem a bit off. The most notable one is grasslands with a temperature of 1.4 (vanilla grasslands are 0.8).
This came up because serene seasons treats biomes with temperature > 0.8 as tropical.

Vanilla MC biomes for rivers, oceans, etc seem to be at 0.5 temperature (except for the actual frozen ones) and tectonic lukewarm river is, indeed, at 0.5.  Though some such as island, lukewarm cliffs and beach are at 0.8- which is mostly only stands out because cold beach is also at 0.8 (copy/paste issue?) while warm beach is at the vanilla 0.5 value for those sorts of biomes.

At a quick glance, most of the rest seem sane, so it's mostly just those few that seem to be at a 0.8 value that maybe were meant to be 0.5 or similar and tectonic grasslands which really stands out at 1.4 (instead of 0.8).

**Comment by ApolloDatapacks** [comment]
Fixed in upcoming version v1.1.5.
