### ISSUE TITLE
All the worlds generated look the same

### ISSUE THREAD

**Issue by Rad233** [ApolloDatapacks/tectonic#13]
Minecraft Version: 1.18.2 fabric
Mod Version: v1.1.4
Environment: 
1. fabric-api-0.67.0+1.18.2
2. tectonic-mod-mc1.18.2-v1.1.4

Description: 
All the worlds generated look the same.

Screenshot: 
https://i.postimg.cc/6QVbcPJS/image.png

**Comment by ApolloDatapacks** [comment]
This is due to a bug in the vanilla game that was patched in 1.19. I can't do anything about it in 1.18.2.

**Comment by Rad233** [comment]
> This is due to a bug in the vanilla game that was patched in 1.19. I can't do anything about it in 1.18.2.

I think this mod fixes that: https://github.com/HyperCubeMC/Seedfix
