### ISSUE TITLE
Underground Rivers creating flat terrain

### ISSUE THREAD

**Issue by Matthysse** [ApolloDatapacks/tectonic#15]
Hello!

Love your datapack, especially the underground rivers, but there is a problem with them: when rivers start to form a cavern, the above terrain remains a river but has no water (obviously) but there are therefore lines of "nothingness" in the landscape, here an example:
![2023-02-05_12 39 43](https://user-images.githubusercontent.com/32510957/216816740-46fe9b7e-7e17-4341-b4de-485a93abeaf6.png)
I use a Terrablender and I don't know if it's an issue that doesn't exist with standalone datapack.

**Comment by ApolloDatapacks** [comment]
This is an issue with how Terrablender works and unfortunately cannot be fixed. Without Terrablender, this issue does not occur.
