### ISSUE TITLE
When I tried to load the normal world again, I couldn't.

### ISSUE THREAD

**Issue by kunieone** [ApolloDatapacks/tectonic#16]
This is a very interesting package, however, I now have an archive that didn't load the package at first, then moved to a client that loads the package (in.minecraft/datapacks), and now when I want to uninstall the package, I find that after I removed it, I can't access the archive. **_"Error in currently selected datapacks prevented world from loading. You can either try to load only with vanilla datapack(" safe mode ") or go back to title screen and fix it manually"_**. How to fix the error? And additionally, the "safe mode” button does not respond when clicked. So I can't load the world without using the datapack. How to solve this problem? I would really appreciate it if you could give me a little solution.

**Comment by ApolloDatapacks** [comment]
You are unable to uninstall this mod without losing access to the world. This is not something that can be fixed as its just due to how the vanilla game works.
