### ISSUE TITLE
riverbed looks strange with some biome mods

### ISSUE THREAD

**Issue by An-thracene** [ApolloDatapacks/tectonic#18]
![image](https://user-images.githubusercontent.com/96624949/220155613-ff2c25b3-4ada-4b73-a71b-4b8bec2bd38b.png)
left: normal riverbed in minecraft:forest; right: strange riverbed in terrestria:cypress_forest
Why is the riverbed full of dirt？？？

**Comment by ApolloDatapacks** [comment]
Fixed in v1.1.9
