### ISSUE TITLE
1.20.1 tectonic (forge) crash with terralith 

### ISSUE THREAD

**Issue by Killeronduty1** [ApolloDatapacks/tectonic#214]
[crash-2024-08-31_06.11.24-server.txt](https://github.com/user-attachments/files/16824675/crash-2024-08-31_06.11.24-server.txt)

**Comment by Apollounknowndev** [comment]
Try updating Terralith to v2.5.4 and see if that fixes the issue.

**Comment by Killeronduty1** [comment]
hey, I commented a while ago although it didn't post. It seems you were correct thanks for the help!

**Comment by Apollounknowndev** [comment]
I'll mark pre-v2.5 Terralith versions as incompatible in the next update.
