### ISSUE TITLE
No dirt in the savanna

### ISSUE THREAD

**Issue by saerdodus** [ApolloDatapacks/tectonic#24]
In the savanna all the dirt is lost.
This problem was present in 1.1.10 mod/DP in 1.18.2, while it worked fine in 1.1.7a.

**Comment by saerdodus** [comment]
And I feel that the world generation of 1.1.10 is much slower than 1.1.7a.

**Comment by ApolloDatapacks** [comment]
Fixed in 1.1.10a.
