### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Aces-and-Jacks** [ApolloDatapacks/tectonic#6]
crashes when generating world https://mclo.gs/FNBkCMb

**Comment by Aces-and-Jacks** [comment]
I saw in a post you said to install https://www.curseforge.com/minecraft/mc-mods/cyanide-fabric and it worked

Would you be able to show this as a dependency?

**Comment by ApolloDatapacks** [comment]
I found the root cause of the crash and fixed it. v1.0.2 should drop the requirement of Cyanide.

**Comment by ApolloDatapacks** [comment]
Closing issue, the crash with Terrablender installed has been fixed in v1.0.1a. Cyanide is still required for BYG/BOP compatibility and still shows that on the wiki.
