### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Aces-and-Jacks** [ApolloDatapacks/tectonic#8]
Tried generating a world after you updated but still crashed https://mclo.gs/PpssU2d

**Comment by Aces-and-Jacks** [comment]
If I went into that  it would crash my game

**Comment by Aces-and-Jacks** [comment]
well I thought it would, went back into the world and it loaded in. only thought it would crash my game because before on any world generation mod that happened

**Comment by Aces-and-Jacks** [comment]
and after flying around this just happened https://mclo.gs/x66Cw9J

**Comment by Aces-and-Jacks** [comment]
ok so reading comments in the terralith mod section I think it's either caused by terrablender or its just my system. I tried terrablender and terralith and crashed. So I think maybe it's just my poor luck and the crashes are caused by something else. no clue


I know you aren't the developer of terralith or terrablendor I was just comparing issues

**Comment by Aces-and-Jacks** [comment]
Ok didn't see Terralith, William Wyther's Overhauled Overworld, and Continents didn't work but still crashes/has trouble loading chunks with just cyanide and your mod

**Comment by ApolloDatapacks** [comment]
Try uninstalling Bedrock Waters and see if that fixed the issues. The crash report seems to link the error to that mod.

**Comment by ApolloDatapacks** [comment]
I just checked the Bedrock Waters CurseForge page. Their newest version should fix the crash. Try it again after updating and let me know if there are any further issues.

**Comment by Aces-and-Jacks** [comment]
guess I forgot to follow updates for them

**Comment by Aces-and-Jacks** [comment]
it works
