### ISSUE TITLE
server timed out due to burried treasure was not found

### ISSUE THREAD

**Issue by rbl-dot** [ApolloDatapacks/tectonic#9]
hello.
so i was playing on my server with friends with some mods, and everything was fine util i went to explore, then i was swimming on boat some blocks, idk 2000 away from land, i found ocean ruins, next opened a loot chest and boom, server timed out.
i asked some people why that happend and they told me its an problem with burried treasure while loot was trying to generate an burried treasure map.

log into console after server time out:
<details>
<summary>Console log</summary>
<pre><code>[16:38:55] [Server Watchdog/ERROR]: A single server tick took 60.00 seconds (should be max 0.05)
[16:38:55] [Server Watchdog/ERROR]: Considering it to be crashed, server will forcibly shutdown.
[16:38:55] [Server Watchdog/ERROR]: This crash report has been saved to: /home/data/rbldot/872738.wom/./crash-reports/crash-2022-11-04_16.38.55-server.txt</code></pre>
</details>

crash log:
[crash-2022-11-04_16.38.55-server.txt](https://github.com/ApolloDatapacks/tectonic/files/9946833/crash-2022-11-04_16.38.55-server.txt)

before that i already has found one burried treasure map and everything was fine.
someone told me it can be tectonic mod making an large continents and thats can be a problem to find burried treasure sometimes.

i'm asking also for change burried treasure spacing/separation, that maybe can fix the problem? idk i'm not really into modding

that's all i think, thanks

**Comment by ApolloDatapacks** [comment]
This is an issue with the vanilla game that I am unable to fix. See [MC-249136](https://bugs.mojang.com/browse/MC-249136) for details.
